---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-hook-sa
  namespace: rook-ceph
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: rook-ceph
  name: ceph-objectstore-backup-restore-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: ["ceph.rook.io"]
    resources: ["cephobjectstores", "cephclusters"]
    verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ceph-objectstore-backup-restore-rolebinding
  namespace: rook-ceph
subjects:
  - kind: ServiceAccount
    name: backup-hook-sa
    namespace: rook-ceph
roleRef:
  kind: Role
  name: ceph-objectstore-backup-restore-role
  apiGroup: rbac.authorization.k8s.io